#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ADFGX_Cloud_Solver_Android.Resource", IsApplication=true)]

namespace ADFGX_Cloud_Solver_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int GoodLabel = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int GoodText = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int LogLabel = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int LogText = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int LogoImage = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int NameLabel = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int NameText = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int NewsButton = 2131165189;
			
			// aapt resource value: 0x7f07000f
			public const int Pbar = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int StartButton = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int StatusLabel = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int StatusText = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int TopScoresButton = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int TriedLabel = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int TriedText = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int adjust_height = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int adjust_width = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout1 = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int none = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gtm_analytics = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int ApplicationName = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int StartString = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_unknown_issue = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
